---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

These plots show the performance of restaurants in terms of inspection scores and grades, by borough. Hover over each plot to get more information.

```{r setup, include=FALSE}
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(flexdashboard)
data("rest_inspec")
rest_inspec <- rest_inspec %>%
  filter(grade == "A" | grade == "B" | grade == "C") %>%
  sample_n(10000)
```


Column {data-width=650}
-----------------------------------------------------------------------
### Distribution of inspection scores, by borough

```{r}
rest_inspec %>%
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")%>%
  layout(xaxis = list(title = "Borough"),
         yaxis = list (title = "Restaurant inspection scores"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Average New York restaurant inspection scores over time, by borough

```{r}
rest_inspec %>% 
  mutate(month = format(inspection_date, "%Y-%m")) %>%
  select(month, boro, score) %>% 
  group_by(month, boro) %>%
  summarize(average = mean(score)) %>%
  ungroup() %>%
  plot_ly(x = ~month, y = ~average, color = ~boro,  type = 'scatter', mode = 'lines+markers', colors = "viridis") %>%
  layout(xaxis = list(title = "Month"),
         yaxis = list (title = "Mean inspection score")) %>%
  hide_legend()
```


### Proportion of restaurants with grades A, B, and C, by borough

```{r}
rest_inspec %>%
  group_by(boro) %>%
  count(grade) %>% 
  mutate(freq = n / sum(n) * 100) %>%
  select(-n) %>%
  pivot_wider(names_from = grade,
              values_from = freq) %>%
  filter(boro != "Missing") %>%
  plot_ly(x = ~boro, y = ~C, name = 'Grade C', type = "bar", 
          marker = list(color = '#CC1480')) %>%
  add_trace(y=~B, name = 'Grade B', marker = list(color = '#FF9673')) %>%   
  add_trace(y=~A, name = 'Grade A', marker = list(color = '#E1C8B4')) %>% 
  layout(barmode = 'stack',
         xaxis = list(title = "Borough"),
         yaxis = list (title = "Proportion of restaurants"))
```